### ISSUE TITLE
App Crash: getTag Null Object reference

### ISSUE THREAD

**Issue by ashishkharcheiu** [mitchtabian/Spotify-Clone#10]
Caused often when pressed `home` button i.e leaving the app and then coming back to it.

Refer master branch.  

    for(Fragment f: MainActivityFragmentManager.getInstance().getFragments()){
            if(f != null ){
                if(!f.getTag().equals(fragment.getTag())){
                    FragmentTransaction t = getSupportFragmentManager().beginTransaction();
                    t.hide(f);
                    t.commit();
                }
            }
        }

 
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.codingwithmitch.audiostreamer/com.codingwithmitch.audiostreamer.ui.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference`
 
     `Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.codingwithmitch.audiostreamer.ui.MainActivity.showFragment(MainActivity.java:380)
        at com.codingwithmitch.audiostreamer.ui.MainActivity.loadFragment(MainActivity.java:363)
        at com.codingwithmitch.audiostreamer.ui.MainActivity.onCreate(MainActivity.java:80)`

**Comment by Zhuinden** [comment]
Also just got this:

```
11-30 06:05:08.737 6303-6303/com.codingwithmitch.audiostreamer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.codingwithmitch.audiostreamer, PID: 6303
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.codingwithmitch.audiostreamer/com.codingwithmitch.audiostreamer.ui.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.codingwithmitch.audiostreamer.ui.MainActivity.showFragment(MainActivity.java:380)
        at com.codingwithmitch.audiostreamer.ui.MainActivity.loadFragment(MainActivity.java:363)
        at com.codingwithmitch.audiostreamer.ui.MainActivity.onCreate(MainActivity.java:80)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```
